### ISSUE TITLE
No Sync

### ISSUE THREAD

**Issue by jongdesteven** [ads04r/aria-spoof#2]
Thanks for this piece of software, it works very well in getting the data on my local computer. However i cannot get my Aria to Sync to Fitbit (no sync on the scale).
Any help is appreciated, my php skills are sub-par so debugging on this side is new to me.

**Comment by ads04r** [comment]
Hi there, apologies for the delay in replying. I've actually not maintained this code for some months now, as I no longer own a working pair of Aria scales and have no way of doing development on this project. I've updated the readme to reflect this. Sorry I can't help.
